# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3f1c47a1dd5f27e8816f15e1d22fd4ad62de07da33a0245cff7ef6050b3cb0eb9cb74021f8eba9c645539d33c0cee7492c8a3f6d66533cde05f72d8cead8ace

test:
  secret_key_base: 5127a415bceefe43f96e652d013175bccdbe7596bd92b8583a419d0943c3947681290f3cab437c615efafa598987698f234aed8fa54a5ab51071c1e691adac3c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
